"""prompts package"""
from .system_prompt import (
    SYSTEM_PROMPT,
    PR_DESCRIPTION_TEMPLATE,
    ISSUE_ANALYSIS_TEMPLATE,
    CODE_REVIEW_TEMPLATE,
    REVIEW_ITEM_TEMPLATE,
)

__all__ = [
    "SYSTEM_PROMPT",
    "PR_DESCRIPTION_TEMPLATE",
    "ISSUE_ANALYSIS_TEMPLATE",
    "CODE_REVIEW_TEMPLATE",
    "REVIEW_ITEM_TEMPLATE",
]
